### ISSUE TITLE
depot locker item duping

### ISSUE THREAD

**Issue by emil92b** [nekiro/TFS-1.4-Downgrades#18]
**Protocol version**
8.60

**Describe the bug**
depot locker item duping

**To Reproduce**
1. go to depot locker
2. open it
3. put in the item of your choice
4. relog

**Expected behavior**
your item has now been duplicated

**Screenshots**
![333](https://user-images.githubusercontent.com/43324808/117746508-d3efec80-b20c-11eb-8648-198db9df2978.png)

**Additional context**
yes i relogged alot ;p im rich af now!
also it does not happen if you put inside the depot chest, so that's good :)

**Comment by Znote** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/1552144/117798833-cf99f280-b251-11eb-9ebd-35196dfd3c78.png)

I actually stumbled upon the same bug yesterday when I did the revert before the official fix in my [8.60-leakydepot](https://github.com/Znote/TFS-1.4-Downgrades/tree/8.60-leakydepot) branch, but I though it was only due to a bad patch job. The branch has a modification that prevents item duplication, presuming depotlocker is empty before server starts. (can be cleared in sql). Anyway you can use this branch temporarily until an official fix is submitted.

**Comment by Znote** [comment]
> Test this commit and let me know [nekiro/forgottenserver@192d220](https://github.com/nekiro/forgottenserver/commit/192d22020e6198b9738586b71b474f67837635e0)

Hehe, yep. Works. :)
